---
abstract: 'tries to shorten hostnames while keeping them meaningful'
author:
  - 'Markus Benning <me@w3r3wolf.de>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-ShortenHostname
requires:
  IO::Handle: 0
  Moose: 0
  MooseX::Getopt: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=String-ShortenHostname
  repository: https://github.com/benningm/String-ShortenHostname
version: 0.003
